### PR TITLE
Created Matplotlib Topic Presentation

### PR DESCRIPTION
**Pull request by catcheu7**
I have used the mysection.qmd file but overriden it. Is there a way to merge without overriding the blank template?

### CODE REVIEW

**Comment by jun-yan** [comment]
+ The folder _book contains all generated files, which should not be tracked. Remember: keep the repo clean.
+ Don't change my template file. Use it to create your own file. See my instruction in Introduction.

**Comment by catcheu7** [comment]
I have updated and cleaned the repository. A new mysection.qmd is added in. Please let me know if there is anything else I need to do.

**Review by jun-yan — CHANGES_REQUESTED** [review]
Could you incorporate my style suggestions, please?

**Comment by catcheu7** [comment]
I put in the style changes. Please let me know if I missed anything. Thank you.

**Comment by jun-yan** [comment]
Could you use better names than ax and ax1? How about fig1 and fig2?

**Comment by catcheu7** [comment]
I changed the figure variables since there would have been a conflict if I just renamed to fig and fig1.

**Pull request merged**
